#!/usr/bin/env python3
"""Export defensive coverage as ATT&CK Navigator layers (stdlib only).

Writes dist/navigator/atlas-coverage.layer.json and attack-coverage.layer.json. Each external
technique ID gets a score from 0 to 3: one point for a linked safe test, one for a detection and
one for a control, taking the best of the LLMInjection techniques that map to it.

Layer format 4.5. The ATLAS layer's `domain` value is an assumption about how an ATLAS-aware
Navigator names its matrix; change it if your Navigator build expects a different value.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from common import ROOT, load_data, write_json  # noqa: E402

OUT = ROOT / "dist" / "navigator"
LEGEND = [("No linked defence", "#e0dacb"), ("One of test, detection, control", "#e9b394"), ("Two of three", "#d4804f"), ("Test, detection and control", "#b43c0e")]


def coverage_by_technique() -> dict[str, dict[str, list[str]]]:
    rels = load_data("relationships")
    out: dict[str, dict[str, list[str]]] = {}
    for t in load_data("techniques"):
        tid = t["id"]
        out[tid] = {
            "tests": sorted(r["source"] for r in rels if r["target"] == tid and r["relationship"] == "validates"),
            "detections": sorted(r["source"] for r in rels if r["target"] == tid and r["relationship"] == "detects"),
            "controls": sorted(r["target"] for r in rels if r["source"] == tid and r["relationship"] == "mitigated-by"),
        }
    return out


def build_layers() -> dict[str, dict]:
    cov, techniques = coverage_by_technique(), load_data("techniques")
    buckets: dict[str, dict[str, dict]] = {"MITRE ATLAS": {}, "MITRE ATT&CK": {}}
    for t in techniques:
        c = cov[t["id"]]
        score = sum(bool(c[k]) for k in ("tests", "detections", "controls"))
        for m in t.get("external_mappings", []):
            bucket = buckets.get(m["framework"])
            if bucket is None:
                continue
            entry = bucket.setdefault(m["id"], {"techniqueID": m["id"], "score": 0, "comments": [], "enabled": True})
            entry["score"] = max(entry["score"], score)
            entry["comments"].append(
                f"{t['id']} {t['name']} ({m['relation']}): tests {', '.join(c['tests']) or 'none'}; "
                f"detections {', '.join(c['detections']) or 'none'}; controls {', '.join(c['controls']) or 'none'}"
            )
    layers = {}
    for framework, filename, domain in (("MITRE ATLAS", "atlas-coverage.layer.json", "atlas"), ("MITRE ATT&CK", "attack-coverage.layer.json", "enterprise-attack")):
        techs = [{**{k: v for k, v in e.items() if k != "comments"}, "comment": " | ".join(e["comments"])} for e in sorted(buckets[framework].values(), key=lambda e: e["techniqueID"])]
        layers[filename] = {
            "name": f"LLMInjection defensive coverage ({framework})",
            "versions": {"layer": "4.5", "navigator": "5.1.0", "attack": "16"},
            "domain": domain,
            "description": "Score = linked safe test + detection + control, from the LLMInjection relationship graph. Generated by scripts/build_navigator.py.",
            "sorting": 3,
            "layout": {"layout": "side", "showID": True, "showName": True},
            "hideDisabled": False,
            "techniques": techs,
            "gradient": {"colors": [LEGEND[0][1], LEGEND[-1][1]], "minValue": 0, "maxValue": 3},
            "legendItems": [{"label": label, "color": color} for label, color in LEGEND],
            "showTacticRowBackground": False,
            "selectTechniquesAcrossTactics": True,
        }
    return layers


def main() -> int:
    for name, layer in build_layers().items():
        write_json(OUT / name, layer)
        print(f"Wrote dist/navigator/{name} ({len(layer['techniques'])} techniques)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
