#!/usr/bin/env python3
"""Generate a concise monthly AI / LLM threat-landscape report from structured data."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data"


def load(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def top_queue_items(queue: dict, limit: int = 10) -> list[dict]:
    active = [
        item for item in queue.get("items", [])
        if item.get("status") in {"candidate", "reviewing"}
    ]
    return sorted(
        active,
        key=lambda item: (
            -int(item.get("relevance_score", 0)),
            str(item.get("published") or ""),
            item.get("title", ""),
        ),
    )[:limit]


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--snapshot", required=True)
    parser.add_argument("--diff", required=True)
    parser.add_argument("--queue", default=str(DATA / "research-queue.json"))
    parser.add_argument("--landscape", default=str(DATA / "threat-landscape-2026.json"))
    parser.add_argument("--output", required=True)
    parser.add_argument("--period", required=True, help="YYYY-MM")
    args = parser.parse_args()

    snapshot = load(Path(args.snapshot))
    diff = load(Path(args.diff))
    queue = load(Path(args.queue))
    landscape = load(Path(args.landscape))

    datasets = snapshot.get("datasets", {})
    summary = diff.get("summary", {})
    domains = landscape.get("domains", [])
    candidates = top_queue_items(queue)

    lines = [
        f"# AI / LLM Threat Landscape Monthly — {args.period}",
        "",
        "> Generated from the LLMInjection evidence model. Candidate intelligence is separated from promoted CTI.",
        "",
        "## Executive delta",
        "",
        f"- Structured records: **{snapshot.get('total_records', 0)}**",
        f"- Added since baseline: **{summary.get('added', 0)}**",
        f"- Removed since baseline: **{summary.get('removed', 0)}**",
        f"- Changed since baseline: **{summary.get('changed', 0)}**",
        f"- Research queue: **{len(queue.get('items', []))}** total candidates",
        "",
        "## Dataset state",
        "",
        "| Dataset | Records |",
        "|---|---:|",
    ]

    for filename, state in sorted(datasets.items()):
        lines.append(f"| {filename} | {state.get('count', 0)} |")

    lines.extend(
        [
            "",
            "## Threat-domain signals",
            "",
            "| Domain | Trend | Confidence | Defensive focus |",
            "|---|---|---|---|",
        ]
    )
    for domain in domains:
        focus = ", ".join(domain.get("defensive_focus", [])[:4])
        lines.append(
            f"| {domain.get('name', '')} | {domain.get('trend', '')} | "
            f"{domain.get('confidence', '')} | {focus} |"
        )

    lines.extend(["", "## Highest-priority research candidates", ""])
    if not candidates:
        lines.append("No unresolved candidates are currently in the research queue.")
    else:
        for item in candidates:
            ids = ", ".join(item.get("identifiers", [])) or "none"
            lines.extend(
                [
                    f"### {item.get('title', '')}",
                    "",
                    f"- Queue ID: {item.get('id')}",
                    f"- Source: {item.get('source_feed_id')} / grade {item.get('source_grade')}",
                    f"- Relevance: **{item.get('relevance_score', 0)}**",
                    f"- Identifiers: {ids}",
                    f"- Published: {item.get('published')}",
                    f"- URL: {item.get('url')}",
                    "",
                    item.get("summary", ""),
                    "",
                ]
            )

    lines.extend(
        [
            "## Analyst note",
            "",
            "This report does not auto-promote collected material. Actor attribution, incident status, external mappings, confidence and vulnerability relationships still require evidence review under docs/METHODOLOGY.md.",
            "",
            "## Machine-readable companions",
            "",
            "- current snapshot: generated by scripts/build_snapshot.py",
            "- change set: generated by scripts/diff_intelligence.py",
            "- research queue: data/research-queue.json",
            "- graph/STIX/API: generated by the existing distribution pipeline",
            "",
        ]
    )

    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines), encoding="utf-8")
    print(f"Generated monthly landscape report: {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
